### ISSUE TITLE
Suggestion: make composite bow extend ItemBow

### ISSUE THREAD

**Issue by Jackiecrazy** [TwilightWingsStudio/CompositeGear#4]
I don't really see any reason why not, considering it's almost a copy-paste, and would make it compatible with stuff that search for instances of ItemBow as well.

**Comment by zcaliptium** [comment]
Hello, friend! 

I didn't extend it from vanilla ``ItemBow`` class just because had idea to make crossbows, slingshots, rifles and other ranged weapons registered using only one this class.

Do you __exactly__ have any problems if it is not ``ItemBow``? Is it related to compatibility with other mods?
It could be cool if you give me example of any other mod which can't understand that my bow is a bow. :)

**Comment by WrongWeekend** [comment]
Dynamic surroundings doesn't provide a drawing sound for the composite bow like the regular bow. There are also some visual effects (like zooming in when drawing the bow) that only apply to ItemBow. I also believe that minecolonies guards can only use bows that are registered as ItemBow.

Just a few examples; I am sure that there are more. Overall the benefits of extending ItemBow would outweigh the drawbacks (if there are any)

**Comment by zcaliptium** [comment]
Hmmmm... With examples now this sounds reasonable.

Okay. I will solve that in a new version.

**Comment by zcaliptium** [comment]
Fixed!
