### ISSUE TITLE
(1.6.2) No Carbon Plate Recipe

### ISSUE THREAD

**Issue by JustHmm** [TwilightWingsStudio/CompositeGear#7]
Hi, im currently playing Absolute Immersive v1.1 modpack which it has CompositeGear-1.12.2-1.6.2 in it. I can't upgrade my helmet to heavy armor because it requires Carbon Plate in somewhere in it (for respirator mask) and modpack doesnt have TR or IC2.  

If i change this in config will it also fix the recipe:

> features_armor {
    # Air mask feature. Restores oxygen level with air cells. TR or IC2 integration required. [default: true]
    B:air_mask=true

Or should i change those:

>     # Industrial Craft 2 Exp. integration. Enables usage of IC2 air cells by air masks. Also magnetizer support for armor. [default: true]
    B:ic2=true

    # TechReborn integration. Enables usage of TR air cells by air masks. [default: true]
    B:techreborn=true

Is mod aware TR and IC2  is avalible or integration settings must manually disabled? I coudn't find anything about carbon plate in config. I dont know did modpack owner missed a config setting or last version coudn't fixed it.

**Comment by zcaliptium** [comment]
Hello!
Ouf... Seems like you found two tiny issues. As I always I miss some small details and got issues. :1st_place_medal: 

1. Yes. There is [Composite Faceplate] that can't be crafted. Due to now way to obtain carbon plate when only IE installed.
2. Air masks won't work without TR or IC2 installed. Because IE haven't item like air cell. ``air_mask`` option in config enables/disables this functionality only if TR or IC2 installed.

Thank you for your report. :+1:   
I'll try to release update with fixes ASAP. I hope I'll be able do that this week, When update will come I'll notify modpack author to request update. :grinning:
