### ISSUE TITLE
Mod Crash

### ISSUE THREAD

**Issue by sscards55** [TwilightWingsStudio/CompositeGear#8]
Composite Gear currently crashed if IC2 Classic is installed, even with the config option disabled. I know that it's intended for IC2 Exp. But I also want to use it with IE installed.

**Comment by zcaliptium** [comment]
Hello! Can you provide crash-log? Can you point exactly what versions of Forge and mods you used?

Btw. Crash can be caused by using too old Forge. For example mod version 1.7.1 built on top of ``14.23.5.2814``. It should be not less than pointed version.

To reproduce crash I tried to run game with latest versions of mods available and latest forge:
 - Forge ``14.23.5.2838``
 - CompositeGear ``1.7.1``
 - IC2 Classic ``2.2.999``
 - ImmersiveEngineering ``0.12-89``

Game runs without crash.

**Comment by sscards55** [comment]
I tried to replicate the issue for a log and it appears a different mod was causing an issue which caused incorrect "blame."

Sorry for bothering you.
